name: Deploy pages
on: push
defaults:
  run: 
    working-directory: slide
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: slidev build --base 2023CSCamp
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: ./slide/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
